[update]
dependants_release_type = 'as-dep'
default_release_type = 'patch'
include_root = false

[publish]
include_monorepo_root = false

[versioning]
unified = true
source = 'tag'

[tagging]
release_tag_package = '@flatom/core'

[release]
tag_only = true

[release_list]
enabled = true
storage = { type = 'branch', branch = 'pvm-resources' }

[changelogs]
enabled = true
storage = { type = 'branch', branch = 'pvm-resources' }
