# This is a basic workflow to help you get started with Actions

name: Check feature

# Controls when the action will run.
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - uses: ./.github/actions/prepare

      - name: Lint
        run: yarn run lint

      - name: Check
        run: yarn run prettier:check

      - name: Build packages
        run: yarn run build

      - name: Testing
        run: yarn test

  publish-info:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - uses: ./.github/actions/prepare

      - run: yarn build

      - name: Mark PR
        run: yarn pvm mark-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
