name: Master

on:
  push:
    branches:
      - 'master'

env:
  PVM_LL: silly

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - uses: ./.github/actions/prepare

      - name: Lint
        run: yarn run lint

      - name: Check
        run: yarn run prettier:check

      - name: Build packages
        run: yarn run build

      - name: Testing
        run: yarn test

  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - uses: ./.github/actions/prepare

      - run: yarn build

      - run: yarn pvm update
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
