name: Master

on:
    push:
        branches:
            - 'master'

env:
    PVM_LL: silly

jobs:
    prepare:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup node
                uses: actions/setup-node@v2
                with:
                    node-version: '16'

            -   name: Cache node modules
                uses: actions/cache@v2
                env:
                    cache-name: cache-node-modules
                with:
                    path: |
                        node_modules
                        */*/node_modules
                    key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

            -   name: Install
                run: yarn install

    test:
        runs-on: ubuntu-latest

        needs:
            - prepare

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup node
                uses: actions/setup-node@v2
                with:
                    node-version: '16'

            -   name: Cache node modules
                uses: actions/cache@v2
                env:
                    cache-name: cache-node-modules
                with:
                    path: |
                        node_modules
                        */*/node_modules
                    key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

            -   name: Lint
                run: yarn run lint

            -   name: Check
                run: yarn run prettier:check

            -   name: Build packages
                run: yarn run build

            -   name: Testing
                run: yarn test

    update:
        runs-on: ubuntu-latest

        needs:
            - prepare

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 100
                    ref: ${{ github.event.pull_request.head.sha }}

            -   name: Setup node
                uses: actions/setup-node@v2
                with:
                    node-version: '16'

            -   name: Cache node modules
                uses: actions/cache@v2
                env:
                    cache-name: cache-node-modules
                with:
                    path: |
                        node_modules
                        */*/node_modules
                    key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

            -   run: yarn build

            -   run: yarn pvm update
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
