# This is a basic workflow to help you get started with Actions

name: Pull request info

# Controls when the action will run.
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review

jobs:
    prepare:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup node
                uses: actions/setup-node@v2
                with:
                    node-version: '16'

            -   name: Cache node modules
                uses: actions/cache@v2
                env:
                    cache-name: cache-node-modules
                with:
                    path: |
                        node_modules
                        */*/node_modules
                    key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

            -   name: Install
                run: yarn install

    publish-info:
        runs-on: ubuntu-latest

        needs:
            - prepare

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 100
                    ref: ${{ github.event.pull_request.head.sha }}

            -   name: Setup node
                uses: actions/setup-node@v2
                with:
                    node-version: '16'

            -   name: Cache node modules
                uses: actions/cache@v2
                env:
                    cache-name: cache-node-modules
                with:
                    path: |
                        node_modules
                        */*/node_modules
                    key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

            -   run: yarn build

            -   name: Mark PR
                run: yarn pvm mark-pr
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
