name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  PVM_LL: silly

permissions:
  contents: read
  pages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - uses: ./.github/actions/prepare

      - run: yarn build

      - run: yarn pvm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
